Models/HomePageViewModels.cs
using AspMVC.Models.EF;
using X.PagedList;

namespace AspMVC.Models
{

    public class HomePageViewModel
    {
        public List<GameCell> featured { get; set; }
        public List<GameCell> lastest { get; set; }
        public List<GameCell> recentPopuplar { get; set; }
        public List<GameCell> recentHighrated { get; set; }

    }

    public class BrowseViewModel
    {
        public IPagedList<GameCell> GameCells { get; set; }

        public List<Genre> Genres { get; set; }

        public List<Platform> Platforms { get; set; }
    }
}

Controllers/HomePageController.cs
using AspMVC.Areas.Identity.Controllers;
using AspMVC.Data;
using AspMVC.Models;
using AspMVC.Models.EF;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using X.PagedList;

namespace AspMVC.Controllers
{
    public class HomePageController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _environment;
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly ILogger<AccountController> _logger;

        public HomePageController(AppDbContext context,
            IWebHostEnvironment environment,
            UserManager<AppUser> userManager,
            SignInManager<AppUser> signInManager,
            ILogger<AccountController> logger)
        {
            _context = context;
            _environment = environment;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;

        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var query = _context.ProjectPages.Include(c => c.ProjectCoverImage).Include(c => c.Ratings);
            var featuredList = await query.OrderByDescending(c => c.ViewCount).Take(14).Select(c => new GameCell
            {
                ProjectId = c.ProjectId,
                Title = c.Title,
                CreatorID = c.CreatorId,
                CreatorName = c.Creator.UserName,
                ShortDescription = c.ShortDescription,
                GenreName = c.Genre.GenreName,
                CoverImage = c.ProjectCoverImage.ProjectCoverImageRelativePath,
                PlatformName = c.Platform.PlatformName,
            }).ToListAsync();

            var latestList = await query.OrderByDescending(c => c.ProjectPageDatePosted).Take(14).Select(c => new GameCell
            {
                ProjectId = c.ProjectId,
                Title = c.Title,
                CreatorID = c.CreatorId,
                CreatorName = c.Creator.UserName,
                ShortDescription = c.ShortDescription,
                GenreName = c.Genre.GenreName,
                CoverImage = c.ProjectCoverImage.ProjectCoverImageRelativePath,
                PlatformName = c.Platform.PlatformName,
            }).ToListAsync();
            var recentPopuplarList = await query.
                Where(x => x.ProjectPageDatePosted.CompareTo(DateTime.Now.AddDays(-30)) >= 0).
                OrderByDescending(c => c.ViewCount).
                Take(14).
                Select(c => new GameCell
                {
                    ProjectId = c.ProjectId,
                    Title = c.Title,
                    CreatorID = c.CreatorId,
                    CreatorName = c.Creator.UserName,
                    ShortDescription = c.ShortDescription,
                    GenreName = c.Genre.GenreName,
                    CoverImage = c.ProjectCoverImage.ProjectCoverImageRelativePath,
                    PlatformName = c.Platform.PlatformName,
                }).ToListAsync();
            var recentHighratedList = await query.Where(x => x.ProjectPageDatePosted.CompareTo(DateTime.Now.AddDays(-30)) >= 0)
                .Where(c => c.Ratings.Count > 0)
                .Take(14)
                .Select(c => new GameCell
                {
                    ProjectId = c.ProjectId,
                    Title = c.Title,
                    CreatorID = c.CreatorId,
                    CreatorName = c.Creator.UserName,
                    ShortDescription = c.ShortDescription,
                    GenreName = c.Genre.GenreName,
                    CoverImage = c.ProjectCoverImage.ProjectCoverImageRelativePath,
                    PlatformName = c.Platform.PlatformName,
                    AverageRating = c.Ratings.Average(c => c.RatingScore)
                }).OrderByDescending(c => c.AverageRating).ToListAsync();
            HomePageViewModel model = new HomePageViewModel()
            {
                featured = featuredList,
                lastest = latestList,
                recentHighrated = recentHighratedList,
                recentPopuplar = recentPopuplarList,
            };
            return View(model);
        }
        [HttpGet("/browse")]
        public async Task<IActionResult> Browse(string? sort, string? price, string? genre, string? when, string? platform, int? page)
        {
            if (_context.ProjectPages == null)
            {
                return Problem("Entity set 'gamestore.ProjectPages'  is null.");
            }
            bool isSort = !string.IsNullOrEmpty(sort);
            bool isPrice = !string.IsNullOrEmpty(price);
            bool isGenre = !string.IsNullOrEmpty(genre);
            bool isWhen = !string.IsNullOrEmpty(when);
            bool isPlatform = !string.IsNullOrEmpty(platform);
            string s = "fdas";
            ViewData[s] = "cxv";


            ViewBag.Sort = isSort ? sort : "" ;
            ViewBag.Price = isPrice ? price : "";
            ViewBag.Genre = isGenre ? genre : "";
            ViewBag.When = isWhen ? when : "";
            ViewBag.Platform = isPlatform ? platform : "";
            List<Genre> genres = _context.Genres.OrderBy(g => g.GenreName).ToList();
            List<Platform> platforms = _context.Platform.OrderBy(g => g.PlatformName).ToList();


            var gameQuery = _context.ProjectPages.Include(c => c.ProjectCoverImage).
                                                    Include(c => c.Creator).
                                                    Include(g => g.Genre).Include(p => p.Platform).
                                                    Take(20);
            if (isSort)
            {
                switch (sort)
                {
                    case "most-popular":
                        gameQuery = gameQuery.OrderByDescending(v => v.ViewCount);
                        break;
                    case "most-recent":
                        gameQuery = gameQuery.OrderByDescending(v => v.ProjectPageDatePosted);
                        break;
                    case "top-rated":
                        gameQuery = gameQuery.Where(v => v.Ratings.Count > 0).OrderByDescending(v => v.Ratings.Average(v => v.RatingScore));
                        break;
                    default:
                        gameQuery = gameQuery.OrderByDescending(v => v.ViewCount);
                        break;
                }
            }
            if (isGenre)
            {
                gameQuery = gameQuery.Where(x => x.Genre.GenreSlug == genre);
            }
            if (isWhen)
            {

                double? days;
                switch (when)
                {

                    case "last-day":
                        days = 1;
                        break;
                    case "last-7-days":
                        days = 7;
                        break;
                    case "last-30-days":
                        days = 30;
                        break;
                    default:
                        days = null;
                        break;
                }
                if (days != null)
                {
                    double value = days.Value;
                    gameQuery = gameQuery.Where(x => x.ProjectPageDatePosted.CompareTo(DateTime.Now.AddDays(-value)) >= 0);
                }

            }
            if (isPlatform)
            {
                gameQuery = gameQuery.Where(x => x.Platform.PlatformSlug == platform);
            }


            var games = gameQuery.Select(c => new GameCell
            {
                ProjectId = c.ProjectId,
                Title = c.Title,
                CreatorID = c.CreatorId,
                CreatorName = c.Creator.UserName,
                ShortDescription = c.ShortDescription,
                GenreName = c.Genre.GenreName,
                CoverImage = c.ProjectCoverImage.ProjectCoverImageRelativePath,
                PlatformName = c.Platform.PlatformName,
            }).ToPagedList(page ?? 1, 30);

            BrowseViewModel vm = new BrowseViewModel()
            {
                GameCells = games,
                Genres = genres,
                Platforms = platforms
            };
            return View(vm);



        }
        [HttpGet("/search")]
        public async Task<IActionResult> Search(string? q)
        {
            if (_context == null)
            {
                return Problem("Entity set  is null.");
            }
            var gamesQuery = _context.ProjectPages.Include(c => c.ProjectCoverImage).Take(21);



            if (!string.IsNullOrEmpty(q))
            {
                gamesQuery = gamesQuery.Where(s => s.Title.Contains(q));

                List<GameCell> games = await gamesQuery.Select(c => new GameCell
                {
                    ProjectId = c.ProjectId,
                    Title = c.Title,
                    CreatorID = c.CreatorId,
                    CreatorName = c.Creator.UserName,
                    ShortDescription = c.ShortDescription,
                    GenreName = c.Genre.GenreName,
                    CoverImage = c.ProjectCoverImage.ProjectCoverImageRelativePath,
                    PlatformName = c.Platform.PlatformName,
                }).ToListAsync();
                ViewData["q"] = q;
                return View(games);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/HomePage/Index.cshtml
@model HomePageViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="index_page page_widget base_widget" id="index">
    <div class="sidebar_shroud"></div>
    <!-- sidebar -->
    <div class="index_sidebar">
        <div class="scrolling_content">
            <div class="sidebar_browse">
                <section class="sidebar_browse_group">
                    <h2>Popular Tags</h2>
                    <div class="browse_filters">
                        <a asp-action="Browse" asp-route-genre="horror">Horror games</a>
                        <a asp-action="Browse" asp-route-genre="action">Action games</a>
                        <a asp-action="Browse" asp-route-sort="most-popular">Popular games</a>
                        <a asp-action="Browse" asp-route-sort="most-recent">Latest games</a>
                        <a asp-action="Browse" asp-route-platform="platform-windows">Games for Windows</a>
                        <a asp-action="Browse" asp-route-platform="platform-android">Games for Android</a>
                    </div>
                </section>
                <section class="sidebar_browse_group">
                    <h2>Browse</h2>
                    <div class="browse_filters">
                        <a asp-controller="HomePage" asp-action="Browse" data-action="browse" title="Browse Games" data-label="game">Games</a>
                        <a title="Randomizer" asp-area="Blog" asp-controller="ProjectPage" asp-action="ProjectRandomizer">
                            <span class="icon icon-shuffle"></span>
                            <span class="text">Randomizer</span>
                        </a>
                    </div>
                </section>
                <section class="sidebar_browse_group">
                    <h2>Games by price</h2>
                    <div class="browse_filters">

                        <a data-action="browse" data-label="free" title="Browse free games" asp-action="Browse" asp-route-price="free">Free games</a>

                    </div>
                </section>
            </div>

        </div>
    </div>


    <div class="main_column">
        <div class="grid_groups">
            <section class="game_section">
                <div class="section_header">
                    <h2>Featured Games</h2>

                    <a asp-action="Browse" asp-route-sort="most-popular" class="button outline forward_link">View all</a>
                </div>
                <div id="featured_game_grid" class="featured_game_grid_widget base_widget">
                    @foreach (var item in Model.featured)
                    {
                        await Html.RenderPartialAsync("~/Views/Shared/_mainPageGameCell.cshtml", item);

                    }
                </div>
            </section>
            <section class="game_section">
                <div class="section_header">
                    <h2>Fresh Games</h2>
                    <a asp-action="Browse" asp-route-sort="most-recent" class="button outline forward_link">View more</a>
                </div>
                <div id="featured_game_grid" class="featured_game_grid_widget base_widget">
                    @foreach (var item in Model.lastest)
                    {
                        await Html.RenderPartialAsync("~/Views/Shared/_mainPageGameCell.cshtml", item);

                    }
                </div>
            </section>
            <section class="game_section">
                <div class="section_header">
                    <h2>Recent Popular</h2>

                    <a asp-action="Browse" asp-route-sort="most-popular" asp-route-when="last-30-days" class="button outline forward_link">View more</a>
                </div>
                <div id="featured_game_grid" class="featured_game_grid_widget base_widget">
                    @foreach (var item in Model.recentPopuplar)
                    {
                        await Html.RenderPartialAsync("~/Views/Shared/_mainPageGameCell.cshtml", item);

                    }
                </div>
            </section>
            <section class="game_section">
                <div class="section_header">
                    <h2>Recent High rated</h2>
                    <a asp-action="Browse" asp-route-sort="top-rated" asp-route-when="last-30-days" class="button outline forward_link">View more</a>
                </div>
                <div id="featured_game_grid" class="featured_game_grid_widget base_widget">
                    @foreach (var item in Model.recentHighrated)
                    {
                        await Html.RenderPartialAsync("~/Views/Shared/_mainPageGameCell.cshtml", item);

                    }
                </div>
            </section>



        </div>
        <div class="see_all_games">
            <strong>Don't see anything you like?</strong>
            <a asp-controller="HomePage" asp-action="Browse" class="button outline">
                View all games <span class="icon icon-arrow-right"></span>
            </a>
            <a data-action="footer" data-label="randomizer" href="/randomizer" class="button outline">
                View something random <span class="icon icon-shuffle"></span>
            </a>
        </div>
    </div>


    <script type="text/template" id="loading_lightbox_tpl">
        <div aria-live="polite" class="lightbox loading_lightbox">
            <div class="loader_outer">
                <div class="loader_label">Loading</div>
                <div class="loader_bar">
                    <div class="loader_bar_slider"></div>
                </div>
            </div>
        </div>
    </script>
    <script type="text/javascript">
        init_Index('#index', {
            "recs_count": 16
        });

    </script>

</div>

Views/HomePage/Search.cshtml
@model List<GameCell>
@{
    ViewData["Title"] = "Search";
    
}

    <div id="header_743962" class="header_widget base_widget small_logo">
    </div>
    <div id="search_5676586" class="search_page grid_results_page page_widget base_widget">
        <div class="search_header grid_header has_filters">
            <h2>Search results for '@ViewData["q"]'</h2>
        </div>
        <div class="grid_outer">
            <div class="game_grid_widget base_widget browse_game_grid" id="game_grid_0">
            @foreach(var item in Model)
            {
                await Html.RenderPartialAsync("~/Views/Shared/_searchPageGameCell.cshtml", item);

            }

            </div>
        </div>
    </div>