Areas/Blog/Models/ProjectPageViewModels/ProjectPageViewModels.cs
using AspMVC.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;
using System.Collections;
using AspMVC.Models.EF;

namespace AspMVC.ViewModels
{
    public class CreatorPageViewModel
    {
        public List<ProjectPageModel> Projects { get; set; }
        public string CreatorName { get; set; }
    }
    public class ProjectPageDetailViewModel
    {
        public ProjectPageModel ProjectPage { get; set; }
        public CommentSectionViewModel CommentSection { get; set; }

        public RatingSectionViewModel? RatingSection { get; set; }
    }
    public class DashboardViewModel
    {
        public IEnumerable<ProjectPageModel> ProjectPages { get;}
    }
    public class CreateProjectPageViewModel
    {
        public int ProjectID { get; set;}
        [Required(ErrorMessage = "Project must have a title")]
        [StringLength(200, MinimumLength = 1, ErrorMessage = "{0} expected text between {1} and {2} characters.")]
        [Display(Name = "Title")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Must create url")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "{0} expected text between {1} and {2} characters.")]
        [RegularExpression(@"^[a-z0-9-]*$", ErrorMessage = "Only use characters from [a-z0-9-]")]
        [Display(Name = "Project Url")]
        public string? Slug { set; get; }

        [Display(Name = "Short Description")]
        [StringLength(400, MinimumLength = 1, ErrorMessage = "{0} expected text between {1} and {2} characters.")]
        public string? ShortDescription { get; set; }


        [Display(Name = "Description")]
        public string? Description { get; set; }
        //Genre
        [Display(Name = "Genre")]
        public int GenreId { get; set; }

        [Display(Name = "Platform")]
        public int PlatformId { get; set; }

        [DataType(DataType.Upload)]
        [Display(Name = "Upload Files")]
        //[FileExtensions(Extensions = "png,jpg,jpeg,gif")]
        //[Required(ErrorMessage = "Chọn một file")]
        public ICollection<IFormFile>? FileUpload { get; set; }
        
        [DataType(DataType.Upload)]
        [Display(Name = "Upload Screenshots")]
        //[FileExtensions(Extensions = "png,jpg,jpeg,gif")]
        //[Required(ErrorMessage = "Chọn một file")]
        public ICollection<IFormFile>? PictureUpload { get; set; }
        [Display(Name = "Upload Cover Image")]
        public IFormFile? CoverPictureUpload { get; set; }

    }
    public class EditProjectPageViewModel : CreateProjectPageViewModel
    {
        public List<ProjectUploadedPicture>? ProjectGallery { get; set; }
        public ProjectUploadedCoverImage? ProjectCover { get; set; }
        [Display(Name = "Remove Cover Image")]
        public RemovePictureCheckBox? RemoveCover { get; set; }
        [Display(Name = "Remove Screenshots")]
        public List<RemovePictureCheckBox>? RemoveGallery { get;set; }
        [Display(Name = "Remove Files")]
        public List<int>? RemoveFileIDs { get; set; }

    }
}

Areas/Blog/Controllers/ProjectPageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspMVC.Data;
using AspMVC.Models;
using Microsoft.AspNetCore.Identity;
using AspMVC.Areas.Identity.Controllers;
using Microsoft.CodeAnalysis;
using Microsoft.AspNetCore.StaticFiles;
using System.Security.Claims;
using AspMVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel.Design;
using AspMVC.Services;
using AspMVC.Models.EF;
using System.Xml.Linq;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Humanizer;

namespace AspMVC.Areas.Blog.Controllers
{
    [Area("Blog")]
    public class ProjectPageController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _environment;
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly ILogger<AccountController> _logger;

        public ProjectPageController(AppDbContext context,
            IWebHostEnvironment environment,
            UserManager<AppUser> userManager,
            SignInManager<AppUser> signInManager,
            ILogger<AccountController> logger)
        {
            _context = context;
            _environment = environment;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;

        }

        // GET: Blog/ProjectPage
        [Authorize(Roles = "Administrator, Member")]

        public async Task<IActionResult> Index()
        {
            var userid = _userManager.GetUserId(HttpContext.User);
            var model = _context.ProjectPages.Where(u => u.CreatorId == userid).Include(p => p.Genre).Include(c=>c.ProjectCoverImage);
            
            return View(await model.ToListAsync());
        }
        public async Task<IActionResult> CreatorPage(string creatorId)
        {
            var games = await _context.ProjectPages.Where(u => u.CreatorId == creatorId).Include(p => p.Genre).Include(c => c.ProjectCoverImage).ToListAsync();
            //var creatorName = _userManager.FindByIdAsync(creatorId);
            var creatorName = (await _context.Users.FirstOrDefaultAsync(u => u.Id == creatorId)).UserName;
            CreatorPageViewModel model = new CreatorPageViewModel()
            {
                Projects = games,
                CreatorName = creatorName,
            };
            return View(model);

        }

        // GET: Blog/ProjectPage/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ProjectPages == null)
            {
                return NotFound();
            }
            string? currentUserName= null;
            string? currentUserID = null;
            if (User.Identity.IsAuthenticated)
            {
                ClaimsPrincipal currentUser = this.User;
                currentUserName = currentUser.Identity.Name;
                currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            }
            

            var projectPage = await _context.ProjectPages
                .Include(p => p.Genre).Include(c => c.Comments).Include(f =>f.ProjectFiles).Include(p => p.ProjectPictures)
                .FirstOrDefaultAsync(m => m.ProjectId == id);
            if (projectPage == null)
            {
                return NotFound();
            }
            var pageCommentsList = await _context.Comments
                .Where(cp => cp.ProjectPageId == id)
                .Include(u => u.Author)
                .OrderByDescending(t => t.TimeStamp)
                .ToListAsync();
            ProjectRating? currentUserRating = null;
            if (!String.IsNullOrEmpty(currentUserID))
            {
                currentUserRating = await _context.ProjectRatings
                .Where(p => p.ProjectPageId == id)
                .Where(p => p.UserId == currentUserID).FirstOrDefaultAsync();
            }
            
            
            
            CommentSectionViewModel commentSectionViewModel = new CommentSectionViewModel()
            {
                PageId = id.Value,
                Comments = pageCommentsList
            };

            ProjectPageDetailViewModel detailViewModel = new ProjectPageDetailViewModel()
            {
                ProjectPage = projectPage,
                CommentSection = commentSectionViewModel,       
            };
            if (currentUserRating != null)
            {
                RatingSectionViewModel ratingSectionViewModel = new RatingSectionViewModel()
                {
                    RatingScore = currentUserRating.RatingScore,
                    PageId = id.Value,
                    UserId = currentUserRating.UserId
                };
                detailViewModel.RatingSection = ratingSectionViewModel;
            }
            else
            {
                RatingSectionViewModel ratingSectionViewModel = new RatingSectionViewModel()
                {

                    PageId = id.Value,
                    UserId = currentUserID
                };
                detailViewModel.RatingSection = ratingSectionViewModel;

            }
            projectPage.ViewCount++;
            _context.SaveChanges();

            return View(detailViewModel);
        }
        [Authorize(Roles = "Administrator, Member")]
        // GET: Blog/ProjectPage/Create
        public IActionResult Create()
        {
            ViewData["GenreId"] = new SelectList(_context.Genres, "GenreId", "GenreName");
            ViewData["PlatformId"] = new SelectList(_context.Platform, "PlatformId", "PlatformName");

            return View();
        }

        // POST: Blog/ProjectPage/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [RequestSizeLimit(300_000_000)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProjectPageViewModel projectPageModel)
        {
            
            if (ModelState.IsValid)
            {
                ClaimsPrincipal currentUser = this.User;
                var currentUserName = currentUser.Identity.Name;
                var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;


                var projectImageStorageDir = Path.Combine(_environment.WebRootPath, "uploads", "Users", currentUserName, "Projects", projectPageModel.Title);
                var projectFileStorageDir = Path.Combine(_environment.ContentRootPath, "Areas", "Blog", "Data", currentUserName, "Projects", projectPageModel.Title);

                ///////////////them ban ghi projectpage moi vao database//////////////////////
                ProjectPageModel projectpage = new ProjectPageModel
                {
                    CreatorId = currentUserID,
                    Title = projectPageModel.Title,
                    ShortDescription = (projectPageModel.ShortDescription != null) ? projectPageModel.ShortDescription : "",
                    Description = (projectPageModel.Description != null) ? projectPageModel.Description : "",
                    GenreId = projectPageModel.GenreId,
                    PlatformId = projectPageModel.PlatformId,
                    Slug = projectPageModel.Slug,
                    ProjectPageDatePosted = DateTime.Now,
                    ProjectFilesDir = projectFileStorageDir,
                    ProjectImagesDir = projectImageStorageDir
                    
                    
                    
                };

                //save  project page moi vao database
                await _context.ProjectPages.AddAsync(projectpage);

                await _context.SaveChangesAsync();
                //////////////////////////////////////////////////

                //xu ly upload file len server va them du lieu vao sql
                //var uploadedProjectPictureList = projectPageModel.PictureUpload;
                //var uploadedProjectFileList = projectPageModel.FileUpload;

                //uploaded file directories
                var projectImageGalleryStorageDir = Path.Combine(projectImageStorageDir, "Screenshots");
                var projectCoverImageDir = Path.Combine(projectImageStorageDir, "CoverImage");

                Directory.CreateDirectory(projectImageStorageDir);
                Directory.CreateDirectory(projectImageGalleryStorageDir);
                Directory.CreateDirectory(projectCoverImageDir);
                Directory.CreateDirectory(projectFileStorageDir);

                //xu ly upload gallery

                if (projectPageModel.PictureUpload != null)
                {
                    foreach (var file in projectPageModel.PictureUpload)
                    {
                        string uploadedFile = Path.Combine(projectImageGalleryStorageDir, file.FileName);
                        using (var fileStream = System.IO.File.Create(uploadedFile))
                        {
                            await file.CopyToAsync(fileStream);
                        }

                        string fileRelativePath = $"/uploads/Users/{currentUserName}/Projects/{projectPageModel.Title}/Screenshots/{file.FileName}";
                        ProjectUploadedPicture addUploadedPicture = new ProjectUploadedPicture()
                        {
                            ProjectPageID = projectpage.ProjectId,
                            ProjectPicture = uploadedFile,
                            ProjectPictureRelativePath = fileRelativePath,
                            PictureName = file.FileName
                        };
                        await _context.ProjectUploadedPicture.AddAsync(addUploadedPicture);
                    }
                }
                //

                //xu ly upload coverimage

Areas/Blog/Views/ProjectPage/Create.cshtml
@model AspMVC.ViewModels.CreateProjectPageViewModel

@{
    ViewData["Title"] = "Create";
}

@if (User.Identity.IsAuthenticated)
{
    var summernote = new Summernote("Description", true, 150, 500);
    @await Html.PartialAsync("_SummerNotePartial",summernote)
}
<h1>Create new project</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" autocomplete="off" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" autocomplete="off" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" autocomplete="off"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Slug" class="control-label"></label>
                <input asp-for="Slug" class="form-control" autocomplete="off" />
                <span asp-validation-for="Slug" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class ="form-control" asp-items="ViewBag.GenreId"></select>
            </div>
            <div class="form-group">
                <label asp-for="PlatformId" class="control-label"></label>
                <select asp-for="PlatformId" class ="form-control" asp-items="ViewBag.PlatformId"></select>
            </div>
            <div class="form-group">
                <label asp-for="FileUpload" class="control-label"></label>
                <input asp-for="FileUpload" class="form-control" multiple/>
                <span asp-validation-for="FileUpload"></span>
            </div>
            <div class="form-group">
                <label asp-for="PictureUpload" class="control-label"></label>
                <input asp-for="PictureUpload" class="form-control" accept="image/*" multiple/>
                <span asp-validation-for="PictureUpload"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoverPictureUpload" class="control-label"></label>
                <input asp-for="CoverPictureUpload" class="form-control" accept="image/*"/>
                <span asp-validation-for="CoverPictureUpload"></span>
            </div>

            <div class="form-group">
                @*<input type="submit" value="Create" class="btn btn-primary" />*@
                <button type="submit" class="btn btn-danger" >Upload</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

Areas/Blog/Views/ProjectPage/CreatorPage.cshtml
@model AspMVC.ViewModels.CreatorPageViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Games and other projects made by @Model.CreatorName</h1>

<div class="album py-5 bg-light">
    <div class="container">

        <div class="row">
            @foreach(var project in Model.Projects)
            {
                <div class="col-md-4">
                    <div class="card" style="width: 18rem;">
                        @if (project.ProjectCoverImage == null)
                        {
                            <a asp-area="Blog" asp-controller="ProjectPage" asp-action="Details" asp-route-id="@project.ProjectId">
                                <img src="/images/no-image.jpg" style="width:100%;  height:200px">
                            </a>
                        }
                        else
                        {
                            <a asp-area="Blog" asp-controller="ProjectPage" asp-action="Details" asp-route-id="@project.ProjectId">
                                <img src="@project.ProjectCoverImage.ProjectCoverImageRelativePath" style="width:100%;  height:200px">
                            </a>
                        }                        
                        <div class="card-body">
                            <a class="card-title link-underline-dark text-black" style="text-decoration: none;" asp-area="Blog" asp-controller="ProjectPage" asp-action="Details" asp-route-id="@project.ProjectId">
                                <h5 class="card-title">@project.Title</h5>
                            </a>
                            <p class="card-text">@project.ShortDescription</p>
                        </div>
                    </div>
                </div>
            }
            
           @* <div dir="auto" class="game_cell has_cover lazy_images" data-game_id="@game.GameId">
                <div style="background-color:#000000;" class="game_thumb">
                    <a tabindex="-1" class="thumb_link game_link" data-action="game_grid" asp-area="Blog" asp-controller="ProjectPage" asp-action="Details" asp-route-id="@game.GameId">
                        <img width="315" class="lazy_loaded" height="250" src="@game.CoverImage" />
                    </a>
                </div>
                <div class="game_cell_data">
                    <div class="game_title">
                        <a data-label="" class="title game_link" asp-area="Blog" asp-controller="ProjectPage" asp-action="Details" asp-route-id="@game.GameId" data-action="game_grid">@game.Title</a>
                    </div>
                    <div title="@game.ShortDescription" class="game_text">@game.ShortDescription</div>
                    <div class="game_author">
                        <a asp-area="Blog" asp-controller="ProjectPage" asp-action="CreatorPage" asp-route-creatorId="@game.CreatorID">@game.CreatorName</a>
                    </div>
                    <div class="game_genre">@game.GenreName</div>
                    <div class="game_platform">
                        <span class="icon icon-windows8" title="Download for Windows" aria-hidden="true"></span>
                    </div>
                </div>
            </div>*@


        </div>
    </div>
</div>
@*<div class="dashboard-column">
    @foreach (var item in Model)
    {
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    @if (item.ProjectCoverImage == null)
                    {
                        <a asp-area="Blog" asp-controller="ProjectPage" asp-action="Details" asp-route-id="@item.ProjectId">
                            <img src="/images/no-image.jpg" alt="..." class="img-fluid" style="height:100px;width:180px">
                        </a>
                    }
                    else
                    {
                        <a asp-area="Blog" asp-controller="ProjectPage" asp-action="Details" asp-route-id="@item.ProjectId">
                            <img src="@item.ProjectCoverImage.ProjectCoverImageRelativePath" class="img-fluid" alt="..." style="height:100px;width:180px">
                        </a>
                    }
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <a class="card-title link-underline-dark text-black" asp-area="Blog" asp-controller="ProjectPage" asp-action="Details" asp-route-id="@item.ProjectId" style="text-decoration: none;">
                            <h5 class="card-title">@item.Title</h5>
                        </a>
                        <a asp-action="Edit" asp-route-id="@item.ProjectId">Edit</a> |
                        <a asp-action="Delete" asp-route-id="@item.ProjectId">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    }


</div>*@

Areas/Blog/Views/ProjectPage/Delete.cshtml
@model AspMVC.Models.ProjectPageModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>@Html.DisplayFor(model => model.Title)</h4>
    <hr />

    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProjectId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Areas/Blog/Views/ProjectPage/Details.cshtml
@model AspMVC.ViewModels.ProjectPageDetailViewModel
@using Microsoft.AspNetCore.Identity
@inject UserManager<AppUser> userManager
@{
    ViewData["Title"] = "Details";
    //var commentSectionVM = new CommentSectionViewModel(){ PageId = Model.Id, Comments = Model.Comments};
}
@{
    string username = "";
    string userid = "";
    bool isLoggedIn = false;
    bool isCreator = false;
    bool isAdmin = false;
    if (User.Identity.IsAuthenticated)
    {
        isLoggedIn = true;

        userid = userManager.GetUserId(User);
        if (userid == Model.ProjectPage.CreatorId)
        {
            isCreator = true;
        }
        if (User.IsInRole("Administrator"))
        {
            isAdmin = true;
        }
    }

}

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous" />
<link rel="stylesheet" href="~/css/demo.css">
<script src="~/lib/summernote/summernote-lite.min.js"></script>
<link rel="stylesheet" href="~/lib/summernote/summernote-lite.min.css" />

<h1>@Model.ProjectPage.Title</h1>

<div class="view_game_page">
    <hr />
    <dl class="row">
        <div class="col">
            <div>
                @Html.Raw(Model.ProjectPage.Description)
            </div>

            <h3>Download:</h3>

            @foreach(var file in Model.ProjectPage.ProjectFiles)
            {
                <div class="mb-1" style="width: 500px;">
                    <a asp-action="Download" asp-route-id="@file.FileID" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">Download</a>
                    <strong class="file-name" title="@file.FileName">@file.FileName</strong>
                    <span>@file.FileSize</span>
                </div>
                

            }
            @if (isLoggedIn && !isCreator)
            {
                await Html.RenderPartialAsync("~/Areas/Blog/Views/Shared/_RatingSection.cshtml", Model.RatingSection);
            }
            @{
                if (isLoggedIn)
                {
                    if (isCreator || isAdmin)
                    {
                        Model.CommentSection.isCreatorOrAdmin = true;
                    }
                }
                await Html.RenderPartialAsync("~/Areas/Blog/Views/Shared/_CommentSection.cshtml", Model.CommentSection);
            }
        </div>
        <div class="col screenshot_list">
            @foreach (var img in Model.ProjectPage.ProjectPictures)
            {
                <img src="@Url.Content(img.ProjectPictureRelativePath)" class="screenshot" />
            }
        </div>
        
    </dl>
</div>





@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

}

Areas/Blog/Views/ProjectPage/Index.cshtml
@model IEnumerable<AspMVC.Models.ProjectPageModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Creator Dashboard</h1>

<p>
    <a class="btn btn-success" asp-action="Create">Create new project</a>
</p>
<div class="dashboard-column">
    @foreach (var item in Model)
    {
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0" style="max-width:100%;height:126px">
                <div class="col-md-4" style="">
                    @if (item.ProjectCoverImage == null)
                    {
                        <a asp-area="Blog" asp-controller="ProjectPage" asp-action="Details" asp-route-id="@item.ProjectId">
                            <img src="/images/no-image.jpg" alt="..." class="img-fluid" style="height:126px;width:180px">
                        </a>
                    }
                    else
                    {
                        <a asp-area="Blog" asp-controller="ProjectPage" asp-action="Details" asp-route-id="@item.ProjectId">
                            <img src="@item.ProjectCoverImage.ProjectCoverImageRelativePath" class="img-fluid" alt="..." style="height:126px;width:180px;object-fit:fill">
                        </a>
                    }
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <a class="card-title link-underline-dark text-black" asp-area="Blog" asp-controller="ProjectPage" asp-action="Details" asp-route-id="@item.ProjectId" style="text-decoration: none;">
                            <h5 class="card-title">@item.Title</h5>
                        </a>
                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.ProjectId">Edit</a> |
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.ProjectId">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    }


</div>